// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmqbAMwdGuVKIdZu22gnf2DI8fJIh6ou8',
    appId: '1:159800055365:web:76816a643b012cd880752c',
    messagingSenderId: '159800055365',
    projectId: 'fyp-v1-login',
    authDomain: 'fyp-v1-login.firebaseapp.com',
    storageBucket: 'fyp-v1-login.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1aIcnpZGSW8_X8xKiIZb3tZXGH0QqJqw',
    appId: '1:159800055365:android:8b7450931b2a46fe80752c',
    messagingSenderId: '159800055365',
    projectId: 'fyp-v1-login',
    storageBucket: 'fyp-v1-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_YPJIkvLybeE4bl-7V6k5feEtF9Atl6w',
    appId: '1:159800055365:ios:472bbd701d90c3e380752c',
    messagingSenderId: '159800055365',
    projectId: 'fyp-v1-login',
    storageBucket: 'fyp-v1-login.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );
}
