
final List<String> surahNames = [
  'Al-Fatiha',
  'Al-Baqara',
  'Aal-E-Imran',
  'An-Nisa',
  'Al-Ma\'idah',
  'Al-An\'am',
  'Al-A\'raf',
  'Al-Anfal',
  'At-Tawbah',
  'Yunus',
  'Hud',
  'Yusuf',
  'Ar-Ra\'d',
  'Ibrahim',
  'Al-Hijr',
  'An-Nahl',
  'Al-Isra',
  'Al-Kahf',
  'Maryam',
  'Ta-Ha',
  'Al-Anbiya',
  'Al-Hajj',
  'Al-Mu\'minun',
  'An-Nur',
  'Al-Furqan',
  'Ash-Shu\'ara',
  'An-Naml',
  'Al-Qasas',
  'Al-Ankabut',
  'Ar-Rum',
  'Luqman',
  'As-Sajda',
  'Al-Ahzab',
  'Saba\'',
  'Fatir',
  'Ya-Sin',
  'As-Saffat',
  'Sad',
  'Az-Zumar',
  'Ghafir',
  'Fussilat',
  'Ash-Shura',
  'Az-Zukhruf',
  'Ad-Dukhan',
  'Al-Jathiyah',
  'Al-Ahqaf',
  'Muhammad',
  'Al-Fath',
  'Al-Hujurat',
  'Qaf',
  'Adh-Dhariyat',
  'At-Tur',
  'An-Najm',
  'Al-Qamar',
  'Ar-Rahman',
  'Al-Waqi\'ah',
  'Al-Hadid',
  'Al-Mujadila',
  'Al-Hashr',
  'Al-Mumtahanah',
  'As-Saff',
  'Al-Jumu\'ah',
  'Al-Munafiqun',
  'At-Taghabun',
  'At-Talaq',
  'At-Tahrim',
  'Al-Mulk',
  'Al-Qalam',
  'Al-Haaqqa',
  'Al-Ma\'arij',
  'Nuh',
  'Al-Jinn',
  'Al-Muzzammil',
  'Al-Muddaththir',
  'Al-Qiyamah',
  'Al-Insan',
  'Al-Mursalat',
  'An-Naba\'',
  'An-Nazi\'at',
  'Abasa',
  'At-Takwir',
  'Al-Infitar',
  'Al-Mutaffifin',
  'Al-Inshiqaq',
  'Al-Buruj',
  'At-Tariq',
  'Al-A\'la',
  'Al-Ghashiyah',
  'Al-Fajr',
  'Al-Balad',
  'Ash-Shams',
  'Al-Lail',
  'Ad-Duhaa',
  'Ash-Sharh',
  'At-Tin',
  'Al-Alaq',
  'Al-Qadr',
  'Al-Bayyinah',
  'Az-Zalzalah',
  'Al-Adiyat',
  'Al-Qari\'ah',
  'At-Takathur',
  'Al-Asr',
  'Al-Humazah',
  'Al-Fil',
  'Quraish',
  'Al-Ma\'un',
  'Al-Kawthar',
  'Al-Kafirun',
  'An-Nasr',
  'Al-Masad',
  'Al-Ikhlas',
  'Al-Falaq',
  'An-Nas',
];

final Map<String, int> surahNameToIndex = {
  for (int i = 0; i < surahNames.length; i++) surahNames[i]: i + 1,
};






//
// final Map<String, int> surahNameToIndex = {
//   'Al-Fatiha': 1,
//   'Al-Baqara': 2,
//   'Aal-E-Imran': 3,
//   'An-Nisa': 4,
//   'Al-Ma\'idah': 5,
//   'Al-An\'am': 6,
//   'Al-A\'raf': 7,
//   'Al-Anfal': 8,
//   'At-Tawbah': 9,
//   'Yunus': 10,
//   'Hud': 11,
//   'Yusuf': 12,
//   'Ar-Ra\'d': 13,
//   'Ibrahim': 14,
//   'Al-Hijr': 15,
//   'An-Nahl': 16,
//   'Al-Isra': 17,
//   'Al-Kahf': 18,
//   'Maryam': 19,
//   'Ta-Ha': 20,
//   'Al-Anbiya': 21,
//   'Al-Hajj': 22,
//   'Al-Mu\'minun': 23,
//   'An-Nur': 24,
//   'Al-Furqan': 25,
//   'Ash-Shu\'ara': 26,
//   'An-Naml': 27,
//   'Al-Qasas': 28,
//   'Al-Ankabut': 29,
//   'Ar-Rum': 30,
//   // Add more Surah names and indices as needed
// };
